# Production environment configuration
# LXC containers for cloudflared, pulse, and bose-soundtouch

default_storage = "local"
default_bridge  = "vmbr0"

# NixOS VMs (cloned from template 9000, built by 'task builder:vm-build')
nixos_vms = {
  "claude-dev" = {
    target_node = "proxmox-pc-3"
    description = "NixOS dev VM for running the Claude Code CLI"
    cores       = 4
    memory      = 8192
    balloon     = 4096
    disks = [{
      type    = "scsi"
      storage = "local-zfs"
      size    = "64G"
      ssd     = 1
      discard = "on"
    }]
    ipconfig0 = "dhcp"
  }
}

# NixOS LXC containers
# Template is set via default_lxc_template variable (auto-generated by 'task lxc-build')
lxc_containers = {
  "svc-cloudflared" = {
    target_node      = "proxmox1"
    description      = "Cloudflare Tunnel daemon"
    cores            = 1
    memory           = 512
    swap             = 256
    rootfs_size      = "8G"
    features_nesting = true # Required for NixOS
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }

  "svc-pulse" = {
    target_node      = "proxmox1"
    description      = "Pulse - Proxmox monitoring"
    cores            = 2
    memory           = 1024
    swap             = 512
    rootfs_size      = "16G"
    features_nesting = true # Required for Docker
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }

  "svc-bose-soundtouch" = {
    target_node      = "proxmox1"
    description      = "AfterTouch - Bose SoundTouch local service"
    cores            = 1
    memory           = 512
    swap             = 256
    rootfs_size      = "8G"
    features_nesting = true # Required for NixOS
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }
}
