# Production environment configuration
# LXC containers for cloudflared, pulse, and bose-soundtouch

default_storage = "local"
default_bridge  = "vmbr0"

# NixOS VMs (cloned from template 9000, built by 'task builder:vm-build')
nixos_vms = {
  "claude-dev" = {
    target_node = "proxmox-pc-3"
    description = "NixOS dev VM for running the Claude Code CLI"
    cores       = 4
    memory      = 8192
    balloon     = 4096
    disks = [{
      type    = "scsi"
      storage = "local-zfs"
      size    = "64G"
      ssd     = 1
      discard = "on"
    }]
    ipconfig0 = "dhcp"
  }
}

# NixOS LXC containers
# Template is set via default_lxc_template variable (auto-generated by 'task lxc-build')
lxc_containers = {
  "svc-cloudflared" = {
    target_node      = "proxmox1"
    description      = "Cloudflare Tunnel daemon"
    cores            = 1
    memory           = 512
    swap             = 256
    rootfs_size      = "8G"
    features_nesting = true # Required for NixOS
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }

  "svc-pulse" = {
    target_node      = "proxmox1"
    description      = "Pulse - Proxmox monitoring"
    cores            = 2
    memory           = 1024
    swap             = 512
    rootfs_size      = "16G"
    features_nesting = true # Required for Docker
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }

  "svc-bose-soundtouch" = {
    target_node      = "proxmox1"
    description      = "AfterTouch - Bose SoundTouch local service"
    cores            = 1
    memory           = 512
    swap             = 256
    rootfs_size      = "8G"
    features_nesting = true # Required for NixOS
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
  }

  # Jellyfin media server with AMD RDNA3 (Phoenix2) VAAPI hardware transcode.
  # NOTE: target_node must be a node with the AMD iGPU and /dev/dri/renderD128.
  # Confirm with `ls -l /dev/dri` on the node before applying, and adjust below.
  "svc-jellyfin" = {
    target_node      = "proxmox1"
    description      = "Jellyfin media server (AMD VAAPI HW transcode)"
    cores            = 4
    memory           = 4096
    swap             = 2048
    rootfs_size      = "16G"
    features_nesting = true # Required for NixOS
    features_fuse    = true # Allow FUSE so rclone can mount the NAS SMB share (native cifs can't mount in an unprivileged LXC)
    networks = [{
      name   = "eth0"
      bridge = "vmbr0"
      ip     = "dhcp"
    }]
    # Managed volume on ZFS so Proxmox Backup + pvesr replication cover the library.
    mountpoints = {
      media = {
        storage = "local-zfs"
        size    = "200G"
        mp      = "/srv/media"
        backup  = true
      }
    }
    # Pass the AMD render node in for VAAPI. gid is the IN-CONTAINER group that
    # will own the device node; use 303 = NixOS's default `render` group so the
    # jellyfin user (a render member) can open it. (Host-side access is handled
    # by the unprivileged passthrough + cgroup, independent of the host's gid.)
    device_passthrough = [{
      path = "/dev/dri/renderD128"
      gid  = 303
    }]
  }
}
